name: Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-spec"]
body:
  - type: markdown
    attributes:
      value: |
        Share a clear problem statement so we can evaluate fit with the roadmap.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem or pain point does this address?
      placeholder: As a ..., I want ..., so that ...
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: Describe the expected behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches considered?
      placeholder: Optional
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Areas affected, users impacted, or risks.
      placeholder: Optional
    validations:
      required: false
